CREATE EXTENSION IF NOT EXISTS citext;

-- ============================================================
-- PROFILES  (the 11 team members)
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
    id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username     CITEXT NOT NULL UNIQUE,
    display_name TEXT,
    avatar_url   TEXT,
    is_active    INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- BRANDS
-- ============================================================
CREATE TABLE IF NOT EXISTS brands (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          CITEXT NOT NULL UNIQUE,
    notes         TEXT,
    is_active     INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    old_source_id BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- VENDORS / SUPPLIERS
-- ============================================================
CREATE TABLE IF NOT EXISTS vendors (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          CITEXT NOT NULL,
    phone         TEXT,
    address       TEXT,
    city          TEXT,
    notes         TEXT,
    is_archived   INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    old_source_id BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- PRODUCT CATALOGUE
-- ============================================================
CREATE TABLE IF NOT EXISTS catalog_products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_model    CITEXT NOT NULL,
    category      TEXT NOT NULL CHECK (category IN (
                      'Machine','Probe','Printer','Accessory','Part','Other'
                  )),
    brand_id      BIGINT REFERENCES brands(id),
    probe_type    TEXT,
    description   TEXT,
    source_info   TEXT,
    old_source_id BIGINT,
    needs_review  INTEGER NOT NULL DEFAULT 0 CHECK (needs_review IN (0, 1)),
    review_note   TEXT,
    is_archived   INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (name_model, brand_id, category)
);

-- ============================================================
-- BATCHES
-- ============================================================
CREATE TABLE IF NOT EXISTS batches (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                CITEXT NOT NULL UNIQUE,
    arrival_date        TEXT NOT NULL,
    vendor_id           BIGINT REFERENCES vendors(id),
    supplier_source     TEXT,
    container_reference TEXT,
    notes               TEXT,
    is_archived         INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- CUSTOMERS
-- ============================================================
CREATE TABLE IF NOT EXISTS customers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    company_name  TEXT,
    phone         TEXT,
    email         TEXT,
    address       TEXT,
    city          TEXT,
    customer_type TEXT NOT NULL DEFAULT 'Customer'
                  CHECK (customer_type IN ('Customer','Dealer','Other')),
    notes         TEXT,
    is_archived   INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    old_source_id BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- WORKSHOPS
-- ============================================================
CREATE TABLE IF NOT EXISTS workshops (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    contact     TEXT,
    phone       TEXT,
    address     TEXT,
    city        TEXT,
    notes       TEXT,
    is_archived INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- DEALERS
-- ============================================================
CREATE TABLE IF NOT EXISTS dealers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    contact     TEXT,
    phone       TEXT,
    address     TEXT,
    city        TEXT,
    notes       TEXT,
    is_archived INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- MACHINES
-- ============================================================
CREATE TABLE IF NOT EXISTS machines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id          TEXT NOT NULL UNIQUE,
    batch_id            BIGINT NOT NULL REFERENCES batches(id),
    catalog_product_id  BIGINT REFERENCES catalog_products(id),
    brand_id            BIGINT REFERENCES brands(id),
    model               TEXT NOT NULL,
    serial_number       TEXT,
    year_of_manufacture TEXT,
    vendor_id           BIGINT REFERENCES vendors(id),
    acquisition_date    TEXT,
    status              TEXT NOT NULL DEFAULT 'In Stock'
                        CHECK (status IN ('In Stock','With Workshop','With Dealer','Sold','Archived')),
    current_location    TEXT NOT NULL DEFAULT 'Company',
    condition           TEXT CHECK (condition IN ('Good','Used','Faulty','Unknown')),
    notes               TEXT,
    is_archived         INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    old_source_id       BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- PROBES
-- ============================================================
CREATE TABLE IF NOT EXISTS probes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_id         CITEXT UNIQUE,
    catalog_product_id  BIGINT REFERENCES catalog_products(id),
    model               TEXT,
    brand_id            BIGINT REFERENCES brands(id),
    serial_number       CITEXT,
    batch_id            BIGINT REFERENCES batches(id),
    vendor_id           BIGINT REFERENCES vendors(id),
    acquisition_date    TEXT,
    status              TEXT NOT NULL DEFAULT 'Available'
                        CHECK (status IN ('Available','With Machine','With Workshop','With Dealer','Sold','Archived')),
    current_location    TEXT NOT NULL DEFAULT 'Company',
    assigned_machine_id BIGINT REFERENCES machines(id),
    condition           TEXT CHECK (condition IN ('Good','Used','Needs Inspection','Damaged','Under Repair')),
    condition_notes     TEXT,
    notes               TEXT,
    needs_review        INTEGER NOT NULL DEFAULT 0 CHECK (needs_review IN (0, 1)),
    review_note         TEXT,
    is_archived         INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    old_source_id       BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- PRINTERS
-- ============================================================
CREATE TABLE IF NOT EXISTS printers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_id         CITEXT UNIQUE,
    catalog_product_id  BIGINT REFERENCES catalog_products(id),
    name_model          TEXT,
    brand_id            BIGINT REFERENCES brands(id),
    serial_number       CITEXT,
    quantity            INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 0),
    batch_id            BIGINT REFERENCES batches(id),
    vendor_id           BIGINT REFERENCES vendors(id),
    acquisition_date    TEXT,
    status              TEXT NOT NULL DEFAULT 'Available'
                        CHECK (status IN ('Available','With Machine','With Workshop','With Dealer','Sold','Archived')),
    current_location    TEXT NOT NULL DEFAULT 'Company',
    assigned_machine_id BIGINT REFERENCES machines(id),
    condition           TEXT CHECK (condition IN ('Good','Used','Needs Inspection','Damaged','Under Repair')),
    condition_notes     TEXT,
    notes               TEXT,
    is_archived         INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    old_source_id       BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- PARTS
-- ============================================================
CREATE TABLE IF NOT EXISTS parts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_id         CITEXT UNIQUE,
    catalog_product_id  BIGINT REFERENCES catalog_products(id),
    name_model          TEXT,
    brand_id            BIGINT REFERENCES brands(id),
    serial_number       CITEXT,
    quantity            INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 0),
    batch_id            BIGINT REFERENCES batches(id),
    vendor_id           BIGINT REFERENCES vendors(id),
    acquisition_date    TEXT,
    status              TEXT NOT NULL DEFAULT 'Available'
                        CHECK (status IN ('Available','With Machine','With Workshop','With Dealer','Sold','Archived')),
    current_location    TEXT NOT NULL DEFAULT 'Company',
    assigned_machine_id BIGINT REFERENCES machines(id),
    condition           TEXT CHECK (condition IN ('Good','Used','Needs Inspection','Damaged','Under Repair')),
    condition_notes     TEXT,
    notes               TEXT,
    needs_review        INTEGER NOT NULL DEFAULT 0 CHECK (needs_review IN (0, 1)),
    review_note         TEXT,
    is_archived         INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    old_source_id       BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- SALES
-- ============================================================
CREATE TABLE IF NOT EXISTS sales (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       BIGINT REFERENCES customers(id),
    sale_date         TEXT NOT NULL,
    sale_price        NUMERIC,
    invoice_reference TEXT,
    notes             TEXT,
    actor_id          UUID REFERENCES profiles(id),
    old_source_id     BIGINT,
    old_trno          TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- SALE ITEMS
-- ============================================================
CREATE TABLE IF NOT EXISTS sale_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id          BIGINT NOT NULL REFERENCES sales(id),
    item_type        TEXT NOT NULL CHECK (item_type IN ('machine','probe','printer','part','other')),
    machine_id       BIGINT REFERENCES machines(id),
    probe_id         BIGINT REFERENCES probes(id),
    printer_id       BIGINT REFERENCES printers(id),
    part_id          BIGINT REFERENCES parts(id),
    item_description TEXT,
    item_serial      TEXT,
    item_price       NUMERIC,
    is_main_item     INTEGER NOT NULL DEFAULT 0 CHECK (is_main_item IN (0, 1)),
    old_source_id    BIGINT
);

-- ============================================================
-- MOVEMENTS
-- ============================================================
CREATE TABLE IF NOT EXISTS movements (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_type     TEXT NOT NULL,
    movement_date     TEXT NOT NULL,
    machine_id        BIGINT REFERENCES machines(id),
    probe_id          BIGINT REFERENCES probes(id),
    printer_id        BIGINT REFERENCES printers(id),
    part_id           BIGINT REFERENCES parts(id),
    workshop_id       BIGINT REFERENCES workshops(id),
    dealer_id         BIGINT REFERENCES dealers(id),
    customer_id       BIGINT REFERENCES customers(id),
    from_location     TEXT,
    to_location       TEXT,
    reason            TEXT,
    condition_notes   TEXT,
    notes             TEXT,
    group_ref         TEXT,
    related_group_ref TEXT,
    reference         TEXT,
    reversed_by_ref   TEXT,
    actor_id          UUID REFERENCES profiles(id),
    old_source_id     BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- REPAIR JOBS
-- ============================================================
CREATE TABLE IF NOT EXISTS repair_jobs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_number           TEXT NOT NULL UNIQUE,
    customer_id          BIGINT REFERENCES customers(id),
    customer_contact     TEXT,
    received_at          TEXT NOT NULL,
    delivered_by         TEXT,
    problem_description  TEXT NOT NULL,
    accessories_received TEXT,
    condition_on_arrival TEXT,
    estimated_cost       NUMERIC,
    final_cost           NUMERIC,
    repair_notes         TEXT,
    status               TEXT NOT NULL DEFAULT 'Received'
                         CHECK (status IN ('Received','In Progress','Awaiting Parts','Ready','Returned','Cancelled')),
    returned_at          TEXT,
    collected_by         TEXT,
    return_notes         TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- REPAIR ITEMS
-- ============================================================
CREATE TABLE IF NOT EXISTS repair_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_job_id  BIGINT NOT NULL REFERENCES repair_jobs(id),
    equipment_type TEXT NOT NULL CHECK (equipment_type IN ('machine','probe','printer','other')),
    name_model     TEXT NOT NULL,
    serial_number  TEXT,
    quantity       INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    notes          TEXT
);

-- ============================================================
-- APP SETTINGS
-- ============================================================
CREATE TABLE IF NOT EXISTS app_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- IMPORT AUDIT LOG
-- ============================================================
CREATE TABLE IF NOT EXISTS imports (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code        TEXT NOT NULL UNIQUE,
    source_filename   TEXT,
    source_type       TEXT DEFAULT 'SQL',
    imported_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    imported_by       TEXT,
    records_total     INTEGER NOT NULL DEFAULT 0,
    records_inserted  INTEGER NOT NULL DEFAULT 0,
    records_skipped   INTEGER NOT NULL DEFAULT 0,
    records_flagged   INTEGER NOT NULL DEFAULT 0,
    notes             TEXT
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_machines_status      ON machines(status);
CREATE INDEX IF NOT EXISTS idx_machines_batch       ON machines(batch_id);
CREATE INDEX IF NOT EXISTS idx_machines_catalog     ON machines(catalog_product_id);
CREATE INDEX IF NOT EXISTS idx_probes_status        ON probes(status);
CREATE INDEX IF NOT EXISTS idx_probes_catalog       ON probes(catalog_product_id);
CREATE INDEX IF NOT EXISTS idx_printers_status      ON printers(status);
CREATE INDEX IF NOT EXISTS idx_parts_status         ON parts(status);
CREATE INDEX IF NOT EXISTS idx_parts_catalog        ON parts(catalog_product_id);
CREATE INDEX IF NOT EXISTS idx_movements_date       ON movements(movement_date);
CREATE INDEX IF NOT EXISTS idx_movements_machine    ON movements(machine_id);
CREATE INDEX IF NOT EXISTS idx_movements_probe      ON movements(probe_id);
CREATE INDEX IF NOT EXISTS idx_movements_printer    ON movements(printer_id);
CREATE INDEX IF NOT EXISTS idx_movements_part       ON movements(part_id);
CREATE INDEX IF NOT EXISTS idx_movements_group      ON movements(group_ref);
CREATE INDEX IF NOT EXISTS idx_movements_reference  ON movements(reference);
CREATE INDEX IF NOT EXISTS idx_movements_actor      ON movements(actor_id);
CREATE INDEX IF NOT EXISTS idx_sales_actor          ON sales(actor_id);
CREATE INDEX IF NOT EXISTS idx_workshops_name       ON workshops(name);
CREATE INDEX IF NOT EXISTS idx_dealers_name         ON dealers(name);
CREATE INDEX IF NOT EXISTS idx_machines_old         ON machines(old_source_id);
CREATE INDEX IF NOT EXISTS idx_probes_old           ON probes(old_source_id);
CREATE INDEX IF NOT EXISTS idx_printers_old         ON printers(old_source_id);
CREATE INDEX IF NOT EXISTS idx_parts_old            ON parts(old_source_id);
CREATE INDEX IF NOT EXISTS idx_repair_jobs_status   ON repair_jobs(status);
CREATE INDEX IF NOT EXISTS idx_catalog_name         ON catalog_products(name_model);
CREATE INDEX IF NOT EXISTS idx_catalog_brand        ON catalog_products(brand_id);
CREATE INDEX IF NOT EXISTS idx_catalog_category     ON catalog_products(category);
CREATE INDEX IF NOT EXISTS idx_brands_name          ON brands(name);
CREATE INDEX IF NOT EXISTS idx_vendors_name         ON vendors(name);
CREATE INDEX IF NOT EXISTS idx_customers_name       ON customers(name);
CREATE INDEX IF NOT EXISTS idx_sales_date           ON sales(sale_date);
CREATE INDEX IF NOT EXISTS idx_sales_customer       ON sales(customer_id);

-- ============================================================
-- SEQUENCES + HELPERS (movement numbers, group refs, internal ids)
-- ============================================================
CREATE SEQUENCE IF NOT EXISTS movement_reference_seq START 1;
CREATE SEQUENCE IF NOT EXISTS probe_internal_seq     START 1;
CREATE SEQUENCE IF NOT EXISTS printer_internal_seq   START 1;
CREATE SEQUENCE IF NOT EXISTS part_internal_seq      START 1;

CREATE OR REPLACE FUNCTION next_movement_reference()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN 'MOV-' || LPAD(nextval('movement_reference_seq')::text, 5, '0');
END;
$$;

CREATE OR REPLACE FUNCTION new_group_ref()
RETURNS TEXT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT left(replace(gen_random_uuid()::text, '-', ''), 12);
$$;

CREATE OR REPLACE FUNCTION next_internal_id(kind TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    seq TEXT;
    prefix TEXT;
BEGIN
    IF kind = 'probe' THEN
        seq := 'probe_internal_seq'; prefix := 'PRB';
    ELSIF kind = 'printer' THEN
        seq := 'printer_internal_seq'; prefix := 'PRT';
    ELSIF kind = 'part' THEN
        seq := 'part_internal_seq'; prefix := 'PART';
    ELSE
        RAISE EXCEPTION 'unknown id kind: %', kind;
    END IF;
    RETURN prefix || '-' || LPAD(nextval(seq)::text, 5, '0');
END;
$$;

-- ============================================================
-- AUTO PROFILE ON SIGNUP
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (id, username, display_name)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
        COALESCE(NEW.raw_user_meta_data->>'display_name',
                 NEW.raw_user_meta_data->>'username',
                 split_part(NEW.email, '@', 1))
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- ROW LEVEL SECURITY  (all members are equal)
-- ============================================================
DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'brands','vendors','catalog_products','batches','customers',
        'workshops','dealers','machines','probes','printers','parts',
        'sales','sale_items','movements','repair_jobs','repair_items',
        'app_settings','imports'
    ] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS "members full access" ON %I', t);
        EXECUTE format(
            'CREATE POLICY "members full access" ON %I FOR ALL TO authenticated USING (true) WITH CHECK (true)',
            t);
    END LOOP;
END $$;

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "profiles read all" ON profiles;
DROP POLICY IF EXISTS "profiles insert self" ON profiles;
DROP POLICY IF EXISTS "profiles update self" ON profiles;
DROP POLICY IF EXISTS "profiles delete self" ON profiles;
CREATE POLICY "profiles read all"   ON profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles insert self" ON profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "profiles update self" ON profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY "profiles delete self" ON profiles FOR DELETE TO authenticated USING (id = auth.uid());

-- ============================================================
-- GRANTS
-- ============================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
