-- ============================================================
-- 0007: PROBE BOXES (where the leftover probes live)
--
--   * a box has a name and holds one probe type (Convex, Linear, ...)
--   * boxes are created from Records, admin only
--   * boxing a probe takes it off its machine, marks it Available and
--     makes the box its location
--   * a probe that leaves stock (moved out, archived, put back on a
--     machine) automatically drops out of its box
-- ============================================================

CREATE TABLE IF NOT EXISTS probe_boxes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    probe_type  TEXT NOT NULL,
    notes       TEXT,
    is_archived INTEGER NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1)),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (name)
);

ALTER TABLE probes
    ADD COLUMN IF NOT EXISTS box_id BIGINT REFERENCES probe_boxes(id)
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_probes_box ON probes(box_id);

ALTER TABLE probe_boxes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read all" ON probe_boxes;
DROP POLICY IF EXISTS "admin write" ON probe_boxes;

CREATE POLICY "read all" ON probe_boxes
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "admin write" ON probe_boxes
    FOR ALL TO authenticated
    USING (public.is_admin()) WITH CHECK (public.is_admin());

GRANT ALL ON probe_boxes TO authenticated;
GRANT USAGE ON SEQUENCE probe_boxes_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.probe_box_guard()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status IS DISTINCT FROM 'Available' OR NEW.is_archived = 1 THEN
        NEW.box_id := NULL;
    END IF;
    IF NEW.assigned_machine_id IS NOT NULL THEN
        NEW.box_id := NULL;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS probes_box_guard ON probes;
CREATE TRIGGER probes_box_guard
    BEFORE UPDATE OF status, assigned_machine_id, is_archived, box_id ON probes
    FOR EACH ROW EXECUTE FUNCTION public.probe_box_guard();
